### ISSUE TITLE
Remark doesn't have text wrapping 

### ISSUE THREAD

**Issue by AbdulrahmanAlRammah** [AY2425S1-CS2103-F10-2/tp#181]
Remark should have text mapping because realistically it could be long.

<img width="958" alt="image" src="https://github.com/user-attachments/assets/de54a002-46f8-4322-87b2-6f1555ff342e">

**Comment by Andrew22Teoh** [comment]
I'm not sure why this is the case, the remarks appear to wrap on my end, as it was fixed in PR #170 
<img width="608" alt="image" src="https://github.com/user-attachments/assets/1a0adfa1-1e18-4bd4-b03f-dc02eaa7c819">

Could you confirm that you have pulled the most recent version from the team repo master?

If anyone else is able to test this on their end, that would be a great help, thanks!

**Comment by AbdulrahmanAlRammah** [comment]
Apologies I didn't have the most recent version pulled.
